# Generated by Django 4.2.4 on 2023-08-18 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_valorant', '0002_alter_video_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=250),
        ),
    ]
